import { 
  ItineraryAdmin, 
  BookOrder, 
  DestinationAdmin, 
  DashboardStats,
  AdminUser
} from '@/types/admin';

export const MOCK_ADMIN_USER: AdminUser = {
  id: '1',
  name: '系统管理员',
  email: 'admin@tripsy.com',
  role: 'super_admin',
  createdAt: new Date('2024-01-01'),
  lastLoginAt: new Date(),
};

export const MOCK_ITINERARIES: ItineraryAdmin[] = [
  {
    id: '1',
    userId: 'user-1',
    userName: '张三',
    userEmail: 'zhangsan@example.com',
    status: 'pending',
    destinations: ['日本东京', '大阪'],
    startDate: new Date('2025-03-15'),
    endDate: new Date('2025-03-22'),
    budget: 30000,
    budgetCurrency: 'CNY',
    transportationType: 'flight',
    travelType: 'family',
    travelerCount: { adults: 2, children: 1, seniors: 0 },
    createdAt: new Date('2025-02-20'),
    updatedAt: new Date('2025-02-20'),
    notes: '希望能有迪士尼乐园的行程',
  },
  {
    id: '2',
    userId: 'user-2',
    userName: '李四',
    userEmail: 'lisi@example.com',
    status: 'planning',
    destinations: ['法国巴黎'],
    startDate: new Date('2025-04-10'),
    endDate: new Date('2025-04-17'),
    budget: 50000,
    budgetCurrency: 'CNY',
    transportationType: 'flight',
    travelType: 'honeymoon',
    travelerCount: { adults: 2, children: 0, seniors: 0 },
    createdAt: new Date('2025-02-19'),
    updatedAt: new Date('2025-02-21'),
    assignedTo: '顾问小王',
  },
  {
    id: '3',
    userId: 'user-3',
    userName: '王五',
    userEmail: 'wangwu@example.com',
    status: 'confirmed',
    destinations: ['泰国曼谷', '普吉岛'],
    startDate: new Date('2025-02-28'),
    endDate: new Date('2025-03-05'),
    budget: 15000,
    budgetCurrency: 'CNY',
    transportationType: 'flight',
    travelType: 'friends',
    travelerCount: { adults: 4, children: 0, seniors: 0 },
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-02-18'),
    assignedTo: '顾问小李',
  },
  {
    id: '4',
    userId: 'user-4',
    userName: '赵六',
    userEmail: 'zhaoliu@example.com',
    status: 'completed',
    destinations: ['云南大理', '丽江'],
    startDate: new Date('2025-02-01'),
    endDate: new Date('2025-02-07'),
    budget: 8000,
    budgetCurrency: 'CNY',
    transportationType: 'self-drive',
    travelType: 'family',
    travelerCount: { adults: 2, children: 2, seniors: 0 },
    createdAt: new Date('2025-01-20'),
    updatedAt: new Date('2025-02-08'),
  },
  {
    id: '5',
    userId: 'user-5',
    userName: '孙七',
    userEmail: 'sunqi@example.com',
    status: 'cancelled',
    destinations: ['新加坡'],
    startDate: new Date('2025-03-01'),
    endDate: new Date('2025-03-05'),
    budget: 12000,
    budgetCurrency: 'CNY',
    transportationType: 'flight',
    travelType: 'solo',
    travelerCount: { adults: 1, children: 0, seniors: 0 },
    createdAt: new Date('2025-02-10'),
    updatedAt: new Date('2025-02-15'),
    notes: '用户主动取消',
  },
];

export const MOCK_ORDERS: BookOrder[] = [
  {
    id: 'order-1',
    userId: 'user-4',
    userName: '赵六',
    userEmail: 'zhaoliu@example.com',
    userPhone: '13800138000',
    itineraryId: '4',
    status: 'completed',
    size: 'A4',
    coverType: 'hardcover',
    pageCount: 48,
    quantity: 1,
    totalAmount: 199,
    currency: 'CNY',
    shippingAddress: {
      name: '赵六',
      phone: '13800138000',
      address: '北京市朝阳区xxx街道xxx号',
      city: '北京',
      province: '北京市',
      postalCode: '100000',
      country: '中国',
    },
    trackingNumber: 'SF1234567890',
    shippingCompany: '顺丰速运',
    paidAt: new Date('2025-02-08'),
    shippedAt: new Date('2025-02-09'),
    deliveredAt: new Date('2025-02-11'),
    createdAt: new Date('2025-02-08'),
    updatedAt: new Date('2025-02-11'),
  },
  {
    id: 'order-2',
    userId: 'user-2',
    userName: '李四',
    userEmail: 'lisi@example.com',
    userPhone: '13900139000',
    itineraryId: '2',
    status: 'paid',
    size: 'A4',
    coverType: 'leather',
    pageCount: 56,
    quantity: 2,
    totalAmount: 498,
    currency: 'CNY',
    shippingAddress: {
      name: '李四',
      phone: '13900139000',
      address: '上海市浦东新区xxx路xxx号',
      city: '上海',
      province: '上海市',
      postalCode: '200000',
      country: '中国',
    },
    paidAt: new Date('2025-02-22'),
    createdAt: new Date('2025-02-21'),
    updatedAt: new Date('2025-02-22'),
  },
  {
    id: 'order-3',
    userId: 'user-3',
    userName: '王五',
    userEmail: 'wangwu@example.com',
    userPhone: '13700137000',
    itineraryId: '3',
    status: 'producing',
    size: 'A5',
    coverType: 'paperback',
    pageCount: 40,
    quantity: 1,
    totalAmount: 99,
    currency: 'CNY',
    shippingAddress: {
      name: '王五',
      phone: '13700137000',
      address: '广州市天河区xxx街xxx号',
      city: '广州',
      province: '广东省',
      postalCode: '510000',
      country: '中国',
    },
    paidAt: new Date('2025-02-19'),
    createdAt: new Date('2025-02-18'),
    updatedAt: new Date('2025-02-20'),
  },
];

export const MOCK_DESTINATIONS: DestinationAdmin[] = [
  {
    id: 'dest-1',
    name: '东京',
    nameEn: 'Tokyo',
    country: '日本',
    city: '东京',
    description: '东京是日本的首都，融合了现代与传统的大都市。从浅草寺的古老韵味到涩谷十字路口的繁华，东京总能给游客带来惊喜。',
    shortDescription: '日本首都，现代与传统交融',
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
      'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800',
    ],
    bestSeason: ['春季', '秋季'],
    suggestedDays: 5,
    isPopular: true,
    sortOrder: 1,
    tags: ['城市观光', '美食', '购物'],
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'dest-2',
    name: '巴黎',
    nameEn: 'Paris',
    country: '法国',
    city: '巴黎',
    description: '巴黎，光之城，浪漫之都。埃菲尔铁塔、卢浮宫、香榭丽舍大街，每一处都是经典。',
    shortDescription: '光之城，浪漫之都',
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
    bestSeason: ['春季', '夏季', '秋季'],
    suggestedDays: 4,
    isPopular: true,
    sortOrder: 2,
    tags: ['浪漫', '艺术', '历史'],
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'dest-3',
    name: '曼谷',
    nameEn: 'Bangkok',
    country: '泰国',
    city: '曼谷',
    description: '曼谷，天使之城。金碧辉煌的寺庙、热情好客的人民、令人垂涎的美食，让人流连忘返。',
    shortDescription: '天使之城，微笑国度',
    imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800',
    bestSeason: ['冬季', '春季'],
    suggestedDays: 3,
    isPopular: true,
    sortOrder: 3,
    tags: ['佛教文化', '美食', '夜市'],
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'dest-4',
    name: '大理',
    nameEn: 'Dali',
    country: '中国',
    city: '大理',
    description: '大理，苍山洱海，风花雪月。白族文化、古城韵味，让心灵得到休憩。',
    shortDescription: '苍山洱海，风花雪月',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    bestSeason: ['春季', '夏季', '秋季'],
    suggestedDays: 3,
    isPopular: true,
    sortOrder: 4,
    tags: ['自然风光', '民族文化', '休闲'],
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalUsers: 1234,
  newUsersToday: 15,
  totalItineraries: 856,
  pendingItineraries: 23,
  totalOrders: 234,
  pendingOrders: 8,
  totalRevenue: 45678,
  revenueThisMonth: 12345,
  popularDestinations: [
    { name: '东京', count: 156 },
    { name: '巴黎', count: 134 },
    { name: '曼谷', count: 120 },
    { name: '大理', count: 98 },
    { name: '新加坡', count: 87 },
  ],
  recentActivities: [
    {
      id: 'act-1',
      type: 'itinerary',
      title: '新行程提交',
      description: '张三提交了东京7日游需求',
      time: new Date(Date.now() - 1000 * 60 * 30),
    },
    {
      id: 'act-2',
      type: 'order',
      title: '新订单支付',
      description: '李四支付了纪念书册订单 ¥498',
      time: new Date(Date.now() - 1000 * 60 * 60 * 2),
    },
    {
      id: 'act-3',
      type: 'user',
      title: '新用户注册',
      description: '王五完成注册',
      time: new Date(Date.now() - 1000 * 60 * 60 * 3),
    },
    {
      id: 'act-4',
      type: 'order',
      title: '订单发货',
      description: '赵六的纪念书册已发货',
      time: new Date(Date.now() - 1000 * 60 * 60 * 5),
    },
  ],
};
